"""Initial migration

Revision ID: 0a6c966f59c9
Revises: 
Create Date: 2025-05-23 08:58:04.273900+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic.operations import ops


# revision identifiers, used by Alembic.
revision: str = '0a6c966f59c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite compatibility
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('family_history', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('insurance_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('insurance_id', sa.String(), nullable=True))
        batch_op.drop_column('user_id')
        batch_op.drop_column('emergency_contact')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('license_number', sa.String(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ADMIN', 'DOCTOR', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'DOCTOR', name='userrole'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('license_number')
        batch_op.drop_column('specialization')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('insurance_id')
        batch_op.drop_column('insurance_provider')
        batch_op.drop_column('emergency_contact_number')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('family_history')
        batch_op.drop_column('address')
        batch_op.drop_column('email')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('full_name')
    # ### end Alembic commands ### 